print("One second...")
import os
import subprocess

os.chdir("adb")

os.system("adb kill-server > nul")
os.system("adb start-server > nul")
os.system("cls")
devices=subprocess.getoutput("adb devices")
print(devices)
print("---------------------------------------")
if "device\n" in devices:
  print("Device found!\n")
  print("Before continuing, please ensure that there are no pre-existing OSBES installations (not including ones that were generated by this program) installed on the device")
  print("Press enter to continue.")
  input()

else: 
  print("Device not found, please check that ADB is set up correctly on your device")
input()