print("!!!IF YOU DON'T KNOW WHAT YOU ARE DOING, DON'T USE THIS!!!")
print("v0.0.1\n")
print("Starting ADB server...")
import os
import subprocess

os.chdir("adb")

os.system("adb kill-server > nul")
os.system("adb start-server > nul")
os.system("cls")
devices=subprocess.getoutput("adb devices")
print(devices)
print("---------------------------------------")
if "device\n" in devices:
  print("Device found!\n")
  print("Before continuing, please ensure that there are no pre-existing OSBES installations (not including ones that were generated by this program) installed on the device\n")
  print("Press enter to continue.")
  input()
  os.system("cls")

  print("Stopping Minecraft process (if open)")
  os.system("adb shell am force-stop com.mojang.minecraftpe")

  print("Removing previous OSBES installation (if present)")
  os.system("adb shell rm -rf /sdcard/games/com.mojang/development_resource_packs/OSBES/")

  print("Copying OSBES directory's files to temporary folder...")
  os.system("rmdir /Q /S ..\\tmp")
  os.system("mkdir ..\\tmp")
  os.system("robocopy ..\\ ..\\tmp /E > nul")

  print("Cleaning up before copying to device...")
  os.system("del ..\\tmp\\Deploy.py")
  os.system("rmdir /Q /S ..\\tmp\\adb > nul")
  os.system("rmdir /Q /S ..\\tmp\\.github > nul")
  os.system("rmdir /Q /S ..\\tmp\\.git > nul")
  os.system("rmdir /Q /S ..\\tmp\\tmp > nul") # I have no idea where this folder is coming from
  
  print("Copying to device...")
  os.system("adb shell mkdir sdcard/games/com.mojang/development_resource_packs/OSBES")
  os.system("adb push ../tmp/. /sdcard/games/com.mojang/development_resource_packs/OSBES/")

  print("Cleaning up")
  os.system("rmdir /Q /S ..\\tmp")

  print("Opening Minecraft...")
  os.system("adb shell monkey -p com.mojang.minecraftpe -c android.intent.category.LAUNCHER 1")

  print("\nDone; Press enter to close")

else: 
  print("Device not found, please check that ADB is set up correctly on your device")
input()