print("!!!IF YOU DON'T KNOW WHAT YOU ARE DOING, DON'T USE THIS!!!\n")
print("Starting ADB server...")
import os
import subprocess

os.chdir("adb")

os.system("adb kill-server > nul")
os.system("adb start-server > nul")
os.system("cls")
devices=subprocess.getoutput("adb devices")
print(devices)
print("---------------------------------------")
if "device\n" in devices:
  print("Device found!\n")
  print("Before continuing, please ensure that there are no pre-existing OSBES installations (not including ones that were generated by this program) installed on the device\n")
  print("Press enter to continue.")
  input()
  os.system("cls")

  print("Stopping Minecraft process (if open)")
  os.system("adb shell am force-stop com.mojang.minecraftpe")

  print("Removing previous OSBES installation (if present)")
  os.system("adb shell rm -rf sdcard/games/com.mojang/development_resource_packs/OSBES/")

  print("Copying OSBES directory's files to temporary folder... (this may take a while)")
  os.system("rmdir /Q /S ..\\tmp")
  os.system("mkdir ..\\tmp")
  os.system("robocopy ..\\ ..\\tmp /E > nul")

  print("Cleaning up before copying to device...")
  os.system("del ..\\tmp\\Deploy.py")
  os.system("rmdir /Q /S ..\\tmp\\adb")
  os.system("rmdir /Q /S ..\\tmp\\.github")
  os.system("rmdir /Q /S ..\\tmp\\.git > nul")
  
  os.system("rmdir /Q /S ..\\tmp")
  print("done")

else: 
  print("Device not found, please check that ADB is set up correctly on your device")
input()